version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: improve-mongodb
    ports:
      - "27017:27017"
    networks:
      - be-network

  backend:
    build:
      context: ./backend/improve
      dockerfile: Dockerfile
    container_name: improve-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - be-network

networks:
  be-network:
    driver: bridge
