services:
  db:
    image: postgres:latest
    container_name: improve-db

  backend:
    build:
      context: ./backend/improve
      dockerfile: Dockerfile
    container_name: improve-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
