services:
  mongodb:
    image: mongo:latest
    container_name: improve-mongodb

  backend:
    build:
      context: ./backend/improve
      dockerfile: Dockerfile
    container_name: improve-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
